version: "1.1"
stages:
  - stage:
      - git-checkout:
          alias: repo
          params:
            depth: 1
  - stage:
      - buildpack:
          alias: zero-icon
          params:
            bp_repo: ((bp.repo.prefix))/dice-bpack-termspa.git
            bp_args:
              PUBLIC_DIR: dist
            context: ${repo}
            modules:
              - name: zero-icon
                path: .
  - stage:
      - release:
          params:
            dice_yml: ${repo}/dice.yml
            replacement_images:
              - ${zero-icon}/pack-result
  - stage:
      - dice:
          alias: deploy
          params:
            release_id_path: ${release}
            time_out: 600
